language: go
go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8

branches:
  only:
    - master

# Don't test vendor directory (go test ./... will test these by default and fsnotify causes problems)
script:
  - go test . ./server ./client ./server/auth ./server/keydb ./log

notifications:
  email:
    recipients:
    - devinlundberg@pinterest.com
    on_success: never
    on_failure: change
env:
  global:
    - GO15VENDOREXPERIMENT=1
